// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/rag.proto

package ragpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	History       string                 `protobuf:"bytes,2,opt,name=history,proto3" json:"history,omitempty"`
	AccData       string                 `protobuf:"bytes,3,opt,name=acc_data,json=accData,proto3" json:"acc_data,omitempty"`
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Face          string                 `protobuf:"bytes,5,opt,name=face,proto3" json:"face,omitempty"` // "физических лиц" или "юридических лиц", желательно прямо в такой форме
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerRequest) Reset() {
	*x = AnswerRequest{}
	mi := &file_proto_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerRequest) ProtoMessage() {}

func (x *AnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerRequest.ProtoReflect.Descriptor instead.
func (*AnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_rag_proto_rawDescGZIP(), []int{0}
}

func (x *AnswerRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AnswerRequest) GetHistory() string {
	if x != nil {
		return x.History
	}
	return ""
}

func (x *AnswerRequest) GetAccData() string {
	if x != nil {
		return x.AccData
	}
	return ""
}

func (x *AnswerRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AnswerRequest) GetFace() string {
	if x != nil {
		return x.Face
	}
	return ""
}

type AnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerResponse) Reset() {
	*x = AnswerResponse{}
	mi := &file_proto_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerResponse) ProtoMessage() {}

func (x *AnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerResponse.ProtoReflect.Descriptor instead.
func (*AnswerResponse) Descriptor() ([]byte, []int) {
	return file_proto_rag_proto_rawDescGZIP(), []int{1}
}

func (x *AnswerResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type ClassifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyRequest) Reset() {
	*x = ClassifyRequest{}
	mi := &file_proto_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRequest) ProtoMessage() {}

func (x *ClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRequest.ProtoReflect.Descriptor instead.
func (*ClassifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_rag_proto_rawDescGZIP(), []int{2}
}

func (x *ClassifyRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ClassifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyResponse) Reset() {
	*x = ClassifyResponse{}
	mi := &file_proto_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyResponse) ProtoMessage() {}

func (x *ClassifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyResponse.ProtoReflect.Descriptor instead.
func (*ClassifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_rag_proto_rawDescGZIP(), []int{3}
}

func (x *ClassifyResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type HumanQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HumanQueryRequest) Reset() {
	*x = HumanQueryRequest{}
	mi := &file_proto_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HumanQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanQueryRequest) ProtoMessage() {}

func (x *HumanQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanQueryRequest.ProtoReflect.Descriptor instead.
func (*HumanQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_rag_proto_rawDescGZIP(), []int{4}
}

func (x *HumanQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type HumanQueryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RephrasedQuery string                 `protobuf:"bytes,1,opt,name=rephrased_query,json=rephrasedQuery,proto3" json:"rephrased_query,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HumanQueryResponse) Reset() {
	*x = HumanQueryResponse{}
	mi := &file_proto_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HumanQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanQueryResponse) ProtoMessage() {}

func (x *HumanQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanQueryResponse.ProtoReflect.Descriptor instead.
func (*HumanQueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_rag_proto_rawDescGZIP(), []int{5}
}

func (x *HumanQueryResponse) GetRephrasedQuery() string {
	if x != nil {
		return x.RephrasedQuery
	}
	return ""
}

var File_proto_rag_proto protoreflect.FileDescriptor

const file_proto_rag_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/rag.proto\x12\x03rag\"\x84\x01\n" +
	"\rAnswerRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x18\n" +
	"\ahistory\x18\x02 \x01(\tR\ahistory\x12\x19\n" +
	"\bacc_data\x18\x03 \x01(\tR\aaccData\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x12\n" +
	"\x04face\x18\x05 \x01(\tR\x04face\"(\n" +
	"\x0eAnswerResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\"'\n" +
	"\x0fClassifyRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"(\n" +
	"\x10ClassifyResponse\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\")\n" +
	"\x11HumanQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"=\n" +
	"\x12HumanQueryResponse\x12'\n" +
	"\x0frephrased_query\x18\x01 \x01(\tR\x0erephrasedQuery2\xce\x01\n" +
	"\n" +
	"RAGService\x12;\n" +
	"\x10GetAnswerToQuery\x12\x12.rag.AnswerRequest\x1a\x13.rag.AnswerResponse\x12<\n" +
	"\rClassifyQuery\x12\x14.rag.ClassifyRequest\x1a\x15.rag.ClassifyResponse\x12E\n" +
	"\x12HumanQueryToPrompt\x12\x16.rag.HumanQueryRequest\x1a\x17.rag.HumanQueryResponseB\bZ\x06/ragpbb\x06proto3"

var (
	file_proto_rag_proto_rawDescOnce sync.Once
	file_proto_rag_proto_rawDescData []byte
)

func file_proto_rag_proto_rawDescGZIP() []byte {
	file_proto_rag_proto_rawDescOnce.Do(func() {
		file_proto_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rag_proto_rawDesc), len(file_proto_rag_proto_rawDesc)))
	})
	return file_proto_rag_proto_rawDescData
}

var file_proto_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_rag_proto_goTypes = []any{
	(*AnswerRequest)(nil),      // 0: rag.AnswerRequest
	(*AnswerResponse)(nil),     // 1: rag.AnswerResponse
	(*ClassifyRequest)(nil),    // 2: rag.ClassifyRequest
	(*ClassifyResponse)(nil),   // 3: rag.ClassifyResponse
	(*HumanQueryRequest)(nil),  // 4: rag.HumanQueryRequest
	(*HumanQueryResponse)(nil), // 5: rag.HumanQueryResponse
}
var file_proto_rag_proto_depIdxs = []int32{
	0, // 0: rag.RAGService.GetAnswerToQuery:input_type -> rag.AnswerRequest
	2, // 1: rag.RAGService.ClassifyQuery:input_type -> rag.ClassifyRequest
	4, // 2: rag.RAGService.HumanQueryToPrompt:input_type -> rag.HumanQueryRequest
	1, // 3: rag.RAGService.GetAnswerToQuery:output_type -> rag.AnswerResponse
	3, // 4: rag.RAGService.ClassifyQuery:output_type -> rag.ClassifyResponse
	5, // 5: rag.RAGService.HumanQueryToPrompt:output_type -> rag.HumanQueryResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_rag_proto_init() }
func file_proto_rag_proto_init() {
	if File_proto_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rag_proto_rawDesc), len(file_proto_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rag_proto_goTypes,
		DependencyIndexes: file_proto_rag_proto_depIdxs,
		MessageInfos:      file_proto_rag_proto_msgTypes,
	}.Build()
	File_proto_rag_proto = out.File
	file_proto_rag_proto_goTypes = nil
	file_proto_rag_proto_depIdxs = nil
}
