# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from server.ragpb import rag_pb2 as proto_dot_rag__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/rag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RAGServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAnswerToQuery = channel.unary_unary(
                '/rag.RAGService/GetAnswerToQuery',
                request_serializer=proto_dot_rag__pb2.AnswerRequest.SerializeToString,
                response_deserializer=proto_dot_rag__pb2.AnswerResponse.FromString,
                _registered_method=True)
        self.ClassifyQuery = channel.unary_unary(
                '/rag.RAGService/ClassifyQuery',
                request_serializer=proto_dot_rag__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=proto_dot_rag__pb2.ClassifyResponse.FromString,
                _registered_method=True)
        self.HumanQueryToPrompt = channel.unary_unary(
                '/rag.RAGService/HumanQueryToPrompt',
                request_serializer=proto_dot_rag__pb2.HumanQueryRequest.SerializeToString,
                response_deserializer=proto_dot_rag__pb2.HumanQueryResponse.FromString,
                _registered_method=True)


class RAGServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAnswerToQuery(self, request, context):
        """Главный энтри поинт
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyQuery(self, request, context):
        """Классификация запроса пользователя
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HumanQueryToPrompt(self, request, context):
        """Улучшаетль промпта
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RAGServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAnswerToQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnswerToQuery,
                    request_deserializer=proto_dot_rag__pb2.AnswerRequest.FromString,
                    response_serializer=proto_dot_rag__pb2.AnswerResponse.SerializeToString,
            ),
            'ClassifyQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyQuery,
                    request_deserializer=proto_dot_rag__pb2.ClassifyRequest.FromString,
                    response_serializer=proto_dot_rag__pb2.ClassifyResponse.SerializeToString,
            ),
            'HumanQueryToPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.HumanQueryToPrompt,
                    request_deserializer=proto_dot_rag__pb2.HumanQueryRequest.FromString,
                    response_serializer=proto_dot_rag__pb2.HumanQueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.RAGService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.RAGService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RAGService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAnswerToQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RAGService/GetAnswerToQuery',
            proto_dot_rag__pb2.AnswerRequest.SerializeToString,
            proto_dot_rag__pb2.AnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RAGService/ClassifyQuery',
            proto_dot_rag__pb2.ClassifyRequest.SerializeToString,
            proto_dot_rag__pb2.ClassifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HumanQueryToPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RAGService/HumanQueryToPrompt',
            proto_dot_rag__pb2.HumanQueryRequest.SerializeToString,
            proto_dot_rag__pb2.HumanQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
