# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/rag.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/rag.proto\x12\x03rag\"^\n\rAnswerRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0f\n\x07history\x18\x02 \x01(\t\x12\x10\n\x08\x61\x63\x63_data\x18\x03 \x01(\t\x12\r\n\x05label\x18\x04 \x01(\t\x12\x0c\n\x04\x66\x61\x63\x65\x18\x05 \x01(\t\" \n\x0e\x41nswerResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\" \n\x0f\x43lassifyRequest\x12\r\n\x05query\x18\x01 \x01(\t\"!\n\x10\x43lassifyResponse\x12\r\n\x05label\x18\x01 \x01(\t\"\"\n\x11HumanQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\"-\n\x12HumanQueryResponse\x12\x17\n\x0frephrased_query\x18\x01 \x01(\t2\xce\x01\n\nRAGService\x12;\n\x10GetAnswerToQuery\x12\x12.rag.AnswerRequest\x1a\x13.rag.AnswerResponse\x12<\n\rClassifyQuery\x12\x14.rag.ClassifyRequest\x1a\x15.rag.ClassifyResponse\x12\x45\n\x12HumanQueryToPrompt\x12\x16.rag.HumanQueryRequest\x1a\x17.rag.HumanQueryResponseB\x07Z\x05ragpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\005ragpb'
  _globals['_ANSWERREQUEST']._serialized_start=24
  _globals['_ANSWERREQUEST']._serialized_end=118
  _globals['_ANSWERRESPONSE']._serialized_start=120
  _globals['_ANSWERRESPONSE']._serialized_end=152
  _globals['_CLASSIFYREQUEST']._serialized_start=154
  _globals['_CLASSIFYREQUEST']._serialized_end=186
  _globals['_CLASSIFYRESPONSE']._serialized_start=188
  _globals['_CLASSIFYRESPONSE']._serialized_end=221
  _globals['_HUMANQUERYREQUEST']._serialized_start=223
  _globals['_HUMANQUERYREQUEST']._serialized_end=257
  _globals['_HUMANQUERYRESPONSE']._serialized_start=259
  _globals['_HUMANQUERYRESPONSE']._serialized_end=304
  _globals['_RAGSERVICE']._serialized_start=307
  _globals['_RAGSERVICE']._serialized_end=513
# @@protoc_insertion_point(module_scope)
