// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Bill struct {
	ID       int64
	UserID   int64
	PdfUrl   sql.NullString
	Amount   string
	Status   string
	IssuedAt time.Time
	DueDate  sql.NullTime
}

type OtpRequest struct {
	ID        int64
	UserID    int64
	OtpCode   string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Session struct {
	ID        int64
	UserID    int64
	Token     string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID         int64
	TelegramID int64
	Phone      sql.NullString
	Email      sql.NullString
	CreatedAt  time.Time
}
